import type { Car } from '../types';
import c5 from '../assets/c5.jpg';
import tesla from '../assets/tesla.webp';
import nissan from '../assets/leaf.jpg';
import kona from '../assets/kuna.avif';

export const DUMMY_CARS: Car[] = [
    {
        id: '1',
        title: 'Citroen C5 Aircross',
        model: 'C5 Aircross',
        year: 2023,
        price: 20000,
        mileage: 131164,
        fuel_type: 'Hybrid (Petrol/Electric)',
        transmission: 'Automatic',
        description: 'Advanced comfort SUV with plug-in hybrid efficiency. Featuring progressive hydraulic cushions and executive interior.',
        images: [c5], // Using existing assets as requested
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Lisbon',
        condition: 'Used',
        engine_cc: 1600,
        num_owners: 1,
        make: 'Citroen',
        color: 'Pearl White',
        registered_in: 'Portugal',
        view_count: 156
    },
    {
        id: '2',
        title: 'Hyundai Kona',
        model: 'Kona',
        year: 2022,
        price: 22500,
        mileage: 113348,
        fuel_type: 'Hybrid (Petrol/Electric)',
        transmission: 'Automatic',
        description: 'Dynamic and versatile hybrid compact SUV. Perfect for city driving with exceptional fuel economy.',
        images: [kona],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Porto',
        condition: 'Used',
        engine_cc: 1600,
        num_owners: 1,
        make: 'Hyundai',
        color: 'Cyber Gray',
        registered_in: 'Portugal',
        view_count: 89
    },
    {
        id: '3',
        title: 'Tesla Model 3',
        model: 'Model 3',
        year: 2021,
        price: 18000,
        mileage: 143172,
        fuel_type: 'Electric',
        transmission: 'Automatic',
        description: 'Cutting-edge electric performance. Autopilot enabled with premium connectivity and long-range battery.',
        images: [tesla],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Lisbon',
        condition: 'Used',
        engine_cc: 0,
        num_owners: 1,
        make: 'Tesla',
        color: 'Solid Black',
        registered_in: 'Portugal',
        view_count: 210
    },
    {
        id: '4',
        title: 'Nissan Leaf',
        model: 'Leaf',
        year: 2020,
        price: 12000,
        mileage: 23977,
        fuel_type: 'Electric',
        transmission: 'Other',
        description: 'Reliable and affordable electric mobility. Excellent condition with low mileage and full service history.',
        images: [nissan],
        status: 'active',
        is_featured: false,
        created_at: new Date().toISOString(),
        city: 'Sintra',
        condition: 'Used',
        engine_cc: 0,
        num_owners: 1,
        make: 'Nissan',
        color: 'Deep Blue',
        registered_in: 'Portugal',
        view_count: 342
    }
];
