import type { Car } from '../types';

export const DUMMY_CARS: Car[] = [
    {
        id: '1',
        title: 'Porsche 911 Carrera S',
        model: '911 Carrera S',
        year: 2023,
        price: 45000000,
        mileage: 1200,
        fuel_type: 'Petrol',
        transmission: 'Automatic',
        description: 'A pristine condition Porsche 911 Carrera S. Ceramic brakes, Sport Chrono package, and custom leather interior.',
        images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80'],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Lahore',
        condition: 'Used',
        engine_cc: 3000,
        num_owners: 1,
        make: 'Porsche',
        color: 'Black Metallic',
        registered_in: 'Lahore',
        view_count: 156
    },
    {
        id: '2',
        title: 'Range Rover Autobiography',
        model: 'Range Rover',
        year: 2022,
        price: 68000000,
        mileage: 5000,
        fuel_type: 'Diesel',
        transmission: 'Automatic',
        description: 'The pinnacle of luxury SUVs. Fully loaded Autobiography trim with rear-seat entertainment and executive seating.',
        images: ['https://di-uploads-pod12.dealerinspire.com/landroverlouisville/uploads/2022/03/Range-Rover-Autobiography.jpg'],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Islamabad',
        condition: 'Used',
        engine_cc: 4400,
        num_owners: 1,
        make: 'Land Rover',
        color: 'Santorini Black',
        registered_in: 'Islamabad',
        view_count: 89
    },
    {
        id: '3',
        title: 'Audi e-tron GT',
        model: 'e-tron GT',
        year: 2023,
        price: 38000000,
        mileage: 0,
        fuel_type: 'Electric',
        transmission: 'Automatic',
        description: 'Brand new fully electric performance sedan. Future of mobility combined with Audi legacy.',
        images: ['https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80'],
        status: 'active',
        is_featured: false,
        created_at: new Date().toISOString(),
        city: 'Karachi',
        condition: 'New',
        engine_cc: 0,
        num_owners: 0,
        make: 'Audi',
        color: 'Daytona Gray',
        registered_in: 'Un-Registered',
        view_count: 210
    },
    {
        id: '4',
        title: 'Mercedes-Benz S-Class S580',
        model: 'S-Class',
        year: 2023,
        price: 55000000,
        mileage: 150,
        fuel_type: 'Petrol',
        transmission: 'Automatic',
        description: 'The ultimate luxury sedan. Featuring the latest MBUX system and Burmester high-end 4D surround sound.',
        images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80'],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Lahore',
        condition: 'New',
        engine_cc: 4000,
        num_owners: 0,
        make: 'Mercedes-Benz',
        color: 'Diamond White',
        registered_in: 'Un-Registered',
        view_count: 342
    },
    {
        id: '5',
        title: 'Lamborghini Urus Performante',
        model: 'Urus',
        year: 2024,
        price: 125000000,
        mileage: 50,
        fuel_type: 'Petrol',
        transmission: 'Automatic',
        description: 'The absolute pinnacle of performance SUVs. Giallo Auge exterior with black alcantara interior.',
        images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&q=80'],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Islamabad',
        condition: 'New',
        engine_cc: 4000,
        num_owners: 0,
        make: 'Lamborghini',
        color: 'Giallo Auge',
        registered_in: 'Un-Registered',
        view_count: 856
    },
    {
        id: '6',
        title: 'Bentley Continental GT V8',
        model: 'Continental GT',
        year: 2022,
        price: 85000000,
        mileage: 3200,
        fuel_type: 'Petrol',
        transmission: 'Automatic',
        description: 'The definitive Grand Tourer. Elegant and powerful, this V8 model offers exceptional craftsmanship.',
        images: ['https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&q=80'],
        status: 'active',
        is_featured: false,
        created_at: new Date().toISOString(),
        city: 'Karachi',
        condition: 'Used',
        engine_cc: 4000,
        num_owners: 1,
        make: 'Bentley',
        color: 'Onyx Black',
        registered_in: 'Sindh',
        view_count: 124
    },
    {
        id: '7',
        title: 'BMW i7 xDrive60',
        model: 'i7',
        year: 2024,
        price: 52000000,
        mileage: 0,
        fuel_type: 'Electric',
        transmission: 'Automatic',
        description: 'The next generation of luxury electric mobility. Features the magnificent theater screen for rear occupants.',
        images: ['https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&q=80'],
        status: 'active',
        is_featured: true,
        created_at: new Date().toISOString(),
        city: 'Lahore',
        condition: 'New',
        engine_cc: 0,
        num_owners: 0,
        make: 'BMW',
        color: 'Frozen Deep Grey',
        registered_in: 'Un-Registered',
        view_count: 420
    }
];
