import type { Car } from '../types';

export const DUMMY_CARS: Car[] = [
    {
        id: '1',
        make: 'Mercedes-Benz',
        model: 'G-Class G63',
        year: 2023,
        price: 320000,
        mileage: 1200,
        fuel_type: 'Petrol',
        transmission: 'Automatic',
        description: 'AMG G63 in Obsidian Black. Fully loaded with premium options.',
        images: ['https://images.unsplash.com/photo-1520031441872-265e4ff70366?auto=format&fit=crop&q=80'],
        features: ['AMG Night Package', 'Burmester Sound', 'Sunroof', 'Massage Seats'],
        status: 'active',
        created_at: new Date().toISOString(),
        city: 'Lisbon',
        owner_id: '1',
        vin: 'MBG63123456789',
        registered_in: 'Portugal',
        title: 'Mercedes-Benz G63 AMG',
        condition: 'Used',
        engine_cc: 4000,
        num_owners: 1,
        color: 'Black',
        view_count: 850
    },
    {
        id: '2',
        make: 'Porsche',
        model: '911 Carrera S',
        year: 2024,
        price: 185000,
        mileage: 500,
        fuel_type: 'Petrol',
        transmission: 'Automatic',
        description: 'Pristine 911 Carrera S with Sport Chrono package.',
        images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80'],
        features: ['Sport Chrono', 'Active Suspension', 'Bose Sound', 'LED Matrix'],
        status: 'active',
        created_at: new Date().toISOString(),
        city: 'Porto',
        owner_id: '1',
        vin: '911CS2024987654',
        registered_in: 'Portugal',
        title: 'Porsche 911 Carrera S',
        condition: 'New',
        engine_cc: 3000,
        num_owners: 0,
        color: 'Silver',
        view_count: 1200
    },
    {
        id: '3',
        make: 'Audi',
        model: 'e-tron GT',
        year: 2023,
        price: 145000,
        mileage: 3500,
        fuel_type: 'Electric',
        transmission: 'Automatic',
        description: 'The pinnacle of electric performance. Experience the future of Audi.',
        images: ['https://images.unsplash.com/photo-1614200187524-dc4b892acf16?auto=format&fit=crop&q=80'],
        features: ['Quattro', 'Virtual Cockpit', 'Matrix LED', 'High Speed Charging'],
        status: 'sold',
        created_at: new Date().toISOString(),
        city: 'Algarve',
        owner_id: '1',
        vin: 'AUDIETRON88776655',
        registered_in: 'Portugal',
        title: 'Audi e-tron GT',
        condition: 'Used',
        engine_cc: 0,
        num_owners: 1,
        color: 'Grey',
        view_count: 950
    },
    {
        id: '4',
        make: 'Range Rover',
        model: 'Autobiography',
        year: 2022,
        price: 210000,
        mileage: 12500,
        fuel_type: 'Diesel',
        transmission: 'Automatic',
        description: 'Unmatched luxury and capability. Properly maintained Autobiography trim.',
        images: ['https://images.unsplash.com/photo-1506015391300-4802dc74de2e?auto=format&fit=crop&q=80'],
        features: ['Executive Seating', 'Soft Close Doors', 'Air Suspension', 'Panoramic Roof'],
        status: 'active',
        created_at: new Date().toISOString(),
        city: 'Lisbon',
        owner_id: '1',
        vin: 'RRVOGUE77665544',
        registered_in: 'Portugal',
        title: 'Range Rover Autobiography',
        condition: 'Used',
        engine_cc: 3000,
        num_owners: 1,
        color: 'Blue',
        view_count: 750
    },
];
